"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Django 기존 앱 (기존 그대로 두기)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # --- 외부 라이브러리 ---
    # 서드파티 — 남이 만들어서 갖다쓰는 앱
    'rest_framework',                 # DRF (이미 있으면 중복 추가 X) / Django JSON API 서버로 만들어주는 층
    'rest_framework.authtoken',       # Token을 DB에 저장하는 "회원증 명단" 테이블
    
    # --- 생성한 앱(내가 만든 앱) ---
    'accounts',
    'library',
]

# 이 프로젝트에서 "사용자는 이걸 지칭한다" 라고 Django 전체에 공표하는 문장
# 형식: "앱 이름.모델이름"
AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# ─────────────────────────────────────────────────────────────────────
# DRF 전역 설정
# view마다 따로 쓰지 않으면 이 곳에 작성한 것이 기본값으로 적용됨.
# 비유: "회사 취업규칙" ─ 부서(view)별로 예외를 두려면 그 뷰(view)에서 덮어쓴다.
# ─────────────────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    # [신원 확인] 요청이 들어왔을 때 "누구인지"를 판별하는 방법 목록
    # 위에서부터 순서대로 시도하고, 순서대로 내려오다가 성공한 곳에서 멈춤
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 회원증 번호(Token)를 Header에 붙여 온 경우 → 앱이 사용할 방식
        'rest_framework.authentication.TokenAuthentication',
        # Browser Cookie로 도달한 경우 → DRF test 화면에서 Login 상태로 Click 시 필요
        'rest_framework.authentication.SessionAuthentication',
    ],
    
    # [출입 통제] 신원 확인이 끝난 뒤 "들어와도 되는지"를 판단
    # IsAuthenticated = Login을 하지 않았다면 모두 401로 돌려보냄
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
