"""create v1.0 tables

Revision ID: 0a6ba7b72cfb
Revises: 
Create Date: 2026-09-19 17:08:06.897379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6ba7b72cfb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('title_norm', sa.String(length=200), nullable=False),
    sa.Column('steam_appid', sa.Integer(), nullable=True),
    sa.Column('released_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games')),
    sa.UniqueConstraint('steam_appid', name=op.f('uq_games_steam_appid'))
    )
    op.create_index(op.f('ix_games_title_norm'), 'games', ['title_norm'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres')),
    sa.UniqueConstraint('name', name=op.f('uq_genres_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=30), nullable=False),
    sa.Column('steam_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('password_hash IS NULL OR email IS NOT NULL', name=op.f('ck_users_password_needs_email')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('steam_id', name=op.f('uq_users_steam_id'))
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('purchased_at', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Integer(), nullable=True),
    sa.Column('playtime_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('review', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=10), server_default='MANUAL', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('MANUAL', 'STEAM')", name=op.f('ck_entries_source_allowed')),
    sa.CheckConstraint("status IN ('BACKLOG', 'PLAYING', 'CLEARED', 'ON_HOLD', 'DROPPED')", name=op.f('ck_entries_status_allowed')),
    sa.CheckConstraint('playtime_minutes >= 0', name=op.f('ck_entries_playtime_not_negative')),
    sa.CheckConstraint('purchase_price >= 0', name=op.f('ck_entries_price_not_negative')),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_entries_rating_range')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_entries_game_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_entries_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entries')),
    sa.UniqueConstraint('user_id', 'game_id', name=op.f('uq_entries_user_id'))
    )
    op.create_index('ix_entries_user_status', 'entries', ['user_id', 'status'], unique=False)
    op.create_table('game_genres',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_genres_game_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_game_genres_genre_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'genre_id', name=op.f('pk_game_genres'))
    )
    op.create_index(op.f('ix_game_genres_genre_id'), 'game_genres', ['genre_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_game_genres_genre_id'), table_name='game_genres')
    op.drop_table('game_genres')
    op.drop_index('ix_entries_user_status', table_name='entries')
    op.drop_table('entries')
    op.drop_table('users')
    op.drop_table('genres')
    op.drop_index(op.f('ix_games_title_norm'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
