"""add steam_genre_id to genres

Revision ID: bfea2aef6bcb
Revises: 0a6ba7b72cfb
Create Date: 2026-09-21 16:02:21.602711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfea2aef6bcb'
down_revision: Union[str, Sequence[str], None] = '0a6ba7b72cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('steam_genre_id', sa.String(length=10), nullable=False))
    op.create_unique_constraint(op.f('uq_genres_steam_genre_id'), 'genres', ['steam_genre_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_genres_steam_genre_id'), 'genres', type_='unique')
    op.drop_column('genres', 'steam_genre_id')
    # ### end Alembic commands ###
