"""add partial unique on games title_norm

Revision ID: 1e1d15e51ba2
Revises: 43b0fb42aaa8
Create Date: 2026-09-21 21:16:15.699394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e1d15e51ba2'
down_revision: Union[str, Sequence[str], None] = '43b0fb42aaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_games_title_norm_manual', 'games', ['title_norm'], unique=True, postgresql_where=sa.text('steam_appid IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_games_title_norm_manual', table_name='games', postgresql_where=sa.text('steam_appid IS NULL'))
    # ### end Alembic commands ###
